site_name: Sandeep Kulkarni

# Theme
theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.sections
        - toc.integrate
        - navigation.top
        - header.autohide
    palette:
        - scheme: default
          toggle:
            icon: material/weather-sunny
            name: Switch to dark mode
        - scheme: slate 
          toggle:
            icon: material/weather-night
            name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    logo: img/sk_logo.png
    favicon: img/sk_favicon.png

# Extras
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/sandeepnkulkarni

# Extensions
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences
    - toc:
          permalink: true

# Plugins
plugins:
    - awesome-pages
    - search: # necessary for search to work
          lang:
              - en
          prebuild_index: true

# Copyright
copyright: Copyright &copy; 2022 Sandeep Kulkarni